name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
      - uses: actions/checkout@v2
      - run: deno lint --unstable

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
      - uses: actions/checkout@v2
      - run: deno fmt --check
